## Data Loading
Import data from all Excel Sheets
1. Clinical Data
2. Proteomics Data
3. Somascan Data

## Add common imports
From /src/01_common_imports.py and from other relevant /src/ files

In [3]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from src.common_imports import *
from src.check_data import show_sheet_overview, show_dataset_structure, inspect_dataset
from src.load_data import load_all_sheets

## Load RA-MAP datasets from Excel files

In [ ]:
data = load_all_sheets()

Loading clinical...
Loading protogen...
Loading somascan...
Done loading

## Show available sheets/tabs in RA-MAP datasets

In [ ]:
show_sheet_overview(data)

All dataset keys:
dict_keys(['df_clinical', 'df_steroids', 'df_meds', 'df_glossary', 'df_Samples', 'df_Samples_Annotation', 'df_expMatrix', 'df_sampMatrix'])

## Dataset structure overview (shape inspection)

In [ ]:
show_dataset_structure(data)

===== DATASET STRUCTURE OVERVIEW =====

df_clinical: 327 rows × 67 columns
df_steroids: 414 rows × 10 columns
df_meds: 2534 rows × 9 columns
df_glossary: 70 rows × 2 columns
df_Samples: 163 rows × 597 columns
df_Samples_Annotation: 593 rows × 63 columns
df_expMatrix: 1310 rows × 253 columns
df_sampMatrix: 237 rows × 73 columns

===== END =====

## Initial inspection of all datasets (preview, columns, data types)

Inspect clinical dataset

In [ ]:
inspect_dataset(data['df_clinical'], "Clinical Data")
inspect_dataset(data['df_steroids'], "Steroid Data")
inspect_dataset(data['df_meds'], "Medication Data")

===== CLINICAL DATA =====

HEAD:

,Patient_ID,Digest,Region,Hub,REGION_HUB,Study,IM.STEROIDS.3MONTHS,ACPA.POSITIVE,RHUEMATOID.FACTOR,DAS28.0M,...,GENDER,HEIGHT,WEIGHT,ALCOHOL_Y_N,CURENT SMOKER,InitialxRAYScore,FinalxRAYScore,Erosive,Hep B serology wk 9 (IU/mL),vaccine centre
0,TAC1000,B1895B6B8F7B325B977C180A25C74D079EFB5EB306693D...,1.0,1.0,1.0,TACERA,ND,Yes ...,Yes ...,7.27,...,Female ...,161,65.2,Yes ...,Yes,0,1,0,NaN,NaN
1,TAC1001,59749E6B6785A9983100DA76AB0AE9484B52B2422AB362...,1.0,1.0,1.0,TACERA,yes,Yes ...,Yes ...,7.83,...,Female ...,160,71.5,No ...,Yes,10,12,0,NaN,NaN
2,TAC1002,9C459B98832CB4E81C90B843BF7A7925D5E01A1A306586...,1.0,1.0,1.0,TACERA,yes,Yes ...,Yes ...,3.43,...,Female ...,175,68,Yes ...,Yes,3,3,0,NaN,NaN
3,TAC1003,308098EB685FC45FA0CA61C88D25D810E16C9DADBBA77C...,1.0,1.0,1.0,TACERA,yes,Yes ...,Yes ...,5.76,...,Female ...,164,68.95,No ...,No,3,2,0,NaN,NaN
4,TAC1004,3A9C04CAA9BBAAE16A20614D827FA3B55AA09C94F69284...,1.0,1.0,1.0,TACERA,ND,Yes ...,Yes ...,6.52,...,Female ...,172,90,Yes ...,No,0,1,0,NaN,NaN

SHAPE:
(327, 67)

DTYPES:
Patient_ID                         str
Digest                             str
Region                         float64
Hub                            float64
REGION_HUB                     float64
                                ...
InitialxRAYScore                object
FinalxRAYScore                  object
Erosive                         object
Hep B serology wk 9 (IU/mL)     object
vaccine centre                     str
Length: 67, dtype: object

MISSING VALUES (top 10):
Hep B serology wk 9 (IU/mL)    294
vaccine centre                 275
FinalxRAYScore                  92
Erosive                         55
InitialxRAYScore                55
Remission(<2.6DAS)              54
HighDisease(>4DAS)              54
Remission month                 54
CRP.9M                          53
Region                          52
dtype: int64

===== STEROID DATA =====

HEAD:

,Digest,Date of Assessment,4. Has the patient received a steroid injection?,Assessment,Steroid,Dose,Unit,Date Given,Joint Injected,Route
0,59749E6B6785A9983100DA76AB0AE9484B52B2422AB362...,2013-02-05 00:00:00,Yes,3,Methylprednisolone Acetate,120.0,1,2013-02-05 00:00:00,19,Intramuscular
1,59749E6B6785A9983100DA76AB0AE9484B52B2422AB362...,2013-02-05 00:00:00,Yes,3,Methylprednisolone Acetate,60.0,1,2013-02-05 00:00:00,12,Intraarticular
2,59749E6B6785A9983100DA76AB0AE9484B52B2422AB362...,2013-02-05 00:00:00,Yes,3,Methylprednisolone Acetate,120.0,1,2013-06-02 00:00:00,19,Intramuscular
3,9C459B98832CB4E81C90B843BF7A7925D5E01A1A306586...,7/23/2013,Yes,3,Methylprednisolone Acetate,120.0,1,2013-08-05 00:00:00,19,Intramuscular
4,9C459B98832CB4E81C90B843BF7A7925D5E01A1A306586...,7/23/2013,Yes,3,Methylprednisolone Acetate,60.0,1,2013-08-05 00:00:00,3,Intraarticular

SHAPE:
(414, 10)

DTYPES:
Digest                                                  str
Date of Assessment                                   object
4. Has the patient received a steroid injection?        str
Assessment                                            int64
Steroid                                                 str
Dose                                                float64
Unit                                                  int64
Date Given                                           object
Joint Injected                                        int64
Route                                                   str
dtype: object

MISSING VALUES (top 10):
Date of Assessment                                  2
Digest                                              0
4. Has the patient received a steroid injection?    0
Assessment                                          0
Steroid                                             0
Dose                                                0
Unit                                                0
Date Given                                          0
Joint Injected                                      0
Route                                               0
dtype: int64

===== MEDICATION DATA =====

HEAD:

,Digest,Date of Assessment,Assessment,RA Medication,Dose,Unit,Frequency,Route,Date Started
0,B1895B6B8F7B325B977C180A25C74D079EFB5EB306693D...,4/29/2013,3,Methotrexate,20.0,1,Weekly,Oral,3/18/2013
1,B1895B6B8F7B325B977C180A25C74D079EFB5EB306693D...,4/29/2013,3,Hydroxychloroquine,200.0,1,Twice daily,Oral,2013-05-02 00:00:00
2,B1895B6B8F7B325B977C180A25C74D079EFB5EB306693D...,4/29/2013,3,Folic Acid,5.0,1,Weekly,Oral,2013-05-02 00:00:00
3,B1895B6B8F7B325B977C180A25C74D079EFB5EB306693D...,7/18/2013,6,Hydroxychloroquine,200.0,1,Twice daily,Oral,2013-05-02 00:00:00
4,B1895B6B8F7B325B977C180A25C74D079EFB5EB306693D...,7/18/2013,6,Methotrexate,20.0,1,Weekly,Oral,3/18/2013

SHAPE:
(2534, 9)

DTYPES:
Digest                    str
Date of Assessment     object
Assessment              int64
RA Medication             str
Dose                  float64
Unit                    int64
Frequency                 str
Route                     str
Date Started           object
dtype: object

MISSING VALUES (top 10):
Dose                  6
Route                 6
Frequency             6
Date of Assessment    5
Digest                0
RA Medication         0
Assessment            0
Unit                  0
Date Started          0
dtype: int64

Inspect gene dataset

In [6]:
inspect_gene_dataset(data['df_Samples'], "Protogen Samples")
inspect_gene_dataset(data['df_Samples_Annotation'], "Sample Annotation")

===== PROTOGEN SAMPLES =====

HEAD:

,ProteinID,GeneID,Gene Symbol,Gene Name,TAC1241_BL,TAC1241_M6,TAC1147_BL,TAC1147_M6,TAC1094_BL,TAC1272_BL,...,TAC1032_BL,TAC1281_BL,TAC1281_M6,TAC1035_M6,TAC1035_BL,TAC1075_M6,TAC1075_BL,TAC1062_BL,TAC1062_M6,VAC2051_BL
0,104740305,2547,XRCC6,X-ray repair complementing defective repair in...,116.5,55.0,181.5,87.5,269.5,159.0,...,35.0,29.5,26.0,465.0,340.5,53.5,101.5,51.0,30.5,54.0
1,104741891,6632,SNRPD1,small nuclear ribonucleoprotein D1 polypeptide...,414.0,317.0,76.0,45.0,424.0,194.0,...,57.0,58.0,49.0,368.0,49.0,70.0,143.0,84.0,58.0,133.0
2,104742995,60,ACTB,"actin, beta",335.0,146.0,236.5,114.0,252.5,799.0,...,227.0,54.0,47.0,357.0,118.0,422.0,650.0,309.0,223.0,190.5
3,104743232,5725,PTBP1,polypyrimidine tract binding protein 1,254.0,117.0,102.5,39.0,309.5,156.0,...,76.0,39.0,33.0,285.5,55.0,65.0,200.0,83.0,58.0,100.0
4,104743420,2237,FEN1,flap structure-specific endonuclease 1,95.0,48.0,53.0,22.0,166.5,56.0,...,27.5,24.0,16.0,370.0,75.5,25.0,42.0,47.0,26.0,70.0

SHAPE:
(163, 597)

DTYPES:
ProteinID       object
GeneID           int64
Gene Symbol        str
Gene Name          str
TAC1241_BL     float64
                ...
TAC1075_M6     float64
TAC1075_BL     float64
TAC1062_BL     float64
TAC1062_M6     float64
VAC2051_BL     float64
Length: 597, dtype: object

MISSING VALUES (top 10):
ProteinID      0
GeneID         0
Gene Symbol    0
Gene Name      0
TAC1241_BL     0
TAC1241_M6     0
TAC1147_BL     0
TAC1147_M6     0
TAC1094_BL     0
TAC1272_BL     0
dtype: int64

DTYPES (sample 20):
ProteinID       object
GeneID           int64
Gene Symbol        str
Gene Name          str
TAC1241_BL     float64
TAC1241_M6     float64
TAC1147_BL     float64
TAC1147_M6     float64
TAC1094_BL     float64
TAC1272_BL     float64
TAC1272_M6     float64
VAC2028_BLb    float64
TAC1096_M6     float64
TAC1096_BL     float64
TAC1041_BL     float64
TAC1041_M6     float64
TAC1107_M6     float64
TAC1107_BL     float64
TAC1186_BL     float64
TAC1186_M6     float64
dtype: object

QUICK NUMERIC SUMMARY:

,count,mean,std,min,25%,50%,75%,max
GeneID,163.0,12647.171779,28679.913603,16.0,3009.0,4841.0,7777.50,203068.0
TAC1241_BL,163.0,1591.205521,5522.663534,28.0,151.5,295.0,759.50,45931.0
TAC1241_M6,163.0,875.058282,3115.163772,25.0,85.0,181.0,390.75,25645.0
TAC1147_BL,163.0,6144.156442,17378.867079,28.0,87.5,181.5,1654.00,101315.0
TAC1147_M6,163.0,2731.460123,7797.234577,13.0,43.5,92.0,734.50,47322.5
TAC1094_BL,163.0,726.754601,1184.072541,66.0,215.0,362.0,782.25,8473.0
TAC1272_BL,163.0,1612.297546,4984.302265,32.0,133.0,333.0,746.75,32579.5
TAC1272_M6,163.0,1024.291411,2836.901352,22.0,98.0,247.0,630.00,19251.0
VAC2028_BLb,163.0,641.907975,1752.045030,28.0,92.5,149.0,423.50,12536.0
TAC1096_M6,163.0,1302.300613,3704.082043,23.0,72.0,163.0,615.25,26691.5

===== SAMPLE ANNOTATION =====

HEAD:

,SampleId,Timepoint,Patient_ID,Digest,Study,IM.STEROIDS.3MONTHS,ACPA.POSITIVE,RHUEMATOID.FACTOR,DAS28.0M,DAS28.3M,...,HEIGHT,WEIGHT,ALCOHOL_Y_N,CURENT SMOKER,Symp_Duration,Initial.Score,Final.Score,Erosive,Hep B serology wk 9 (IU/mL),vaccine centre
0,TAC1241_BL,BL,TAC1241,608CAC12FA322B4798E2E772CE6C9F0087B4933ADB8C3A...,TACERA,yes,No ...,Yes ...,6.91,7.02,...,NaN,56.6,No ...,Yes,137,9,18,0,NaN,NaN
1,TAC1241_M6,M6,TAC1241,608CAC12FA322B4798E2E772CE6C9F0087B4933ADB8C3A...,TACERA,yes,No ...,Yes ...,6.91,7.02,...,NaN,56.6,No ...,Yes,137,9,18,0,NaN,NaN
2,TAC1147_BL,BL,TAC1147,E856EB9AC7C85B70C9F42C4F6786775FE65DCDFDE2FB71...,TACERA,ND,ND,Yes ...,7.45,3.09,...,175,121,Yes ...,No,84,36,39,1,NaN,NaN
3,TAC1147_M6,M6,TAC1147,E856EB9AC7C85B70C9F42C4F6786775FE65DCDFDE2FB71...,TACERA,ND,ND,Yes ...,7.45,3.09,...,175,121,Yes ...,No,84,36,39,1,NaN,NaN
4,TAC1094_BL,BL,TAC1094,10433449E77D5E82E36A52EC5518583272BB0FD55D9BC4...,TACERA,ND,Yes ...,Yes ...,5.1,ND,...,190,70.1,Yes ...,Yes,155,0,NaN,0,NaN,NaN

SHAPE:
(593, 63)

DTYPES:
SampleId                          str
Timepoint                         str
Patient_ID                        str
Digest                            str
Study                             str
                                ...
Initial.Score                  object
Final.Score                    object
Erosive                        object
Hep B serology wk 9 (IU/mL)    object
vaccine centre                    str
Length: 63, dtype: object

MISSING VALUES (top 10):
Hep B serology wk 9 (IU/mL)    531
vaccine centre                 500
Final.Score                    144
CRP.9M                          95
Initial.Score                   94
Erosive                         94
ACPA.POSITIVE                   93
DAS28.18M                       93
HAQ.0M                          93
DAS28.12M                       93
dtype: int64

DTYPES (sample 20):
SampleId                  str
Timepoint                 str
Patient_ID                str
Digest                    str
Study                     str
IM.STEROIDS.3MONTHS       str
ACPA.POSITIVE             str
RHUEMATOID.FACTOR         str
DAS28.0M               object
DAS28.3M               object
DAS28.6M               object
DAS28.9M               object
DAS28.12M              object
DAS28.18M              object
HAQ.0M                 object
HAQ.6M                 object
SDAI.0M                object
SDAI.6M                object
SDAI.12M               object
BASOPHILS.0M           object
dtype: object

QUICK NUMERIC SUMMARY:

,count,unique,top,freq
SampleId,593,593,TAC1241_BL,1
Timepoint,593,2,BL,320
Patient_ID,593,318,VAC2028,3
Digest,590,315,BF52DEBA448F1808A5E83ECE257B5AA937E761B02C0F4B...,3
Study,593,2,TACERA,500
IM.STEROIDS.3MONTHS,502,5,yes,241
ACPA.POSITIVE,500,6,Yes ...,403
RHUEMATOID.FACTOR,500,4,Yes ...,426
DAS28.0M,500.0,200.0,6.08,8.0
DAS28.3M,500,203,ND,27

Inspect protein dataset

In [7]:
inspect_protein_dataset(data['df_expMatrix'], "Expression Matrix")
inspect_protein_dataset(data['df_sampMatrix'], "Sample Matrix")

===== EXPRESSION MATRIX =====

HEAD:

,EntrezGeneSymbol,TAC1145_Baseline,TAC1075_6month,TAC1000_Baseline,TAC1058_Baseline,TAC1150_Baseline,TAC1148_6month,TAC1179_6month,TAC1225_6month,TAC1174_Baseline,...,EntrezGeneID,Organism,Units,Type,Dilution,CalReference,Cal_Set_03,ColCheck,Cal_Set_02,Cal_Set_01
0,VEGFA,16301.7,11993.7,10421.1,9352.7,11279.3,11000.8,15116.4,12873.1,10622.2,...,7422,Human,RFU,Protein,40.0,9638.70,1.009,PASS,0.943,1.080
1,TNFRSF1A,1628.1,1358.4,1220.8,1337.1,1355.2,1087.1,1205.6,2062.8,1062.2,...,7132,Human,RFU,Protein,1.0,977.45,0.893,PASS,0.930,0.912
2,MMP3,689.4,585.6,426.4,668.6,390.8,602.3,382.9,1243.5,671.9,...,4314,Human,RFU,Protein,40.0,442.55,0.855,PASS,0.921,0.855
3,VCAM1,12386.8,14119.3,11669.8,15387.8,12320.6,13485.6,13505.8,20003.1,16307.8,...,7412,Human,RFU,Protein,1.0,11100.00,0.984,PASS,0.990,1.012
4,RETN,1732.7,997.0,1042.4,2402.8,1350.4,1186.2,1155.5,1864.4,1323.5,...,56729,Human,RFU,Protein,1.0,1310.85,0.800,PASS,0.780,0.809

SHAPE:
(1310, 253)

DTYPES:
EntrezGeneSymbol        str
TAC1145_Baseline    float64
TAC1075_6month      float64
TAC1000_Baseline    float64
TAC1058_Baseline    float64
                     ...
CalReference        float64
Cal_Set_03          float64
ColCheck                str
Cal_Set_02          float64
Cal_Set_01          float64
Length: 253, dtype: object

MISSING VALUES (top 10):
EntrezGeneID        12
TAC1145_Baseline     0
TAC1075_6month       0
TAC1000_Baseline     0
EntrezGeneSymbol     0
TAC1150_Baseline     0
TAC1148_6month       0
TAC1179_6month       0
TAC1225_6month       0
TAC1174_Baseline     0
dtype: int64

DTYPES (sample 20):
EntrezGeneSymbol        str
TAC1145_Baseline    float64
TAC1075_6month      float64
TAC1000_Baseline    float64
TAC1058_Baseline    float64
TAC1150_Baseline    float64
TAC1148_6month      float64
TAC1179_6month      float64
TAC1225_6month      float64
TAC1174_Baseline    float64
TAC1209_6month      float64
TAC1242_Baseline    float64
VAC2042_Baseline    float64
TAC1217_6month      float64
TAC1119_6month      float64
TAC1139_Baseline    float64
VAC2005_Baseline    float64
TAC1073_6month      float64
TAC1127_6month      float64
TAC1016_Baseline    float64
dtype: object

SUMMARY STATISTICS (first 10 proteins):

,count,mean,std,min,25%,50%,75%,max
TAC1145_Baseline,1310.0,8108.284733,25574.280225,45.3,534.250,1306.35,4215.900,299042.9
TAC1075_6month,1310.0,7843.922137,23466.891731,36.8,535.850,1376.10,4462.450,254452.0
TAC1000_Baseline,1310.0,9521.327099,27388.674550,39.5,522.600,1468.40,5672.975,277157.7
TAC1058_Baseline,1310.0,7203.232290,21905.230310,38.3,499.000,1197.65,3908.150,248989.5
TAC1150_Baseline,1310.0,8158.718092,24825.590423,56.3,504.175,1418.75,5029.925,275795.1
TAC1148_6month,1310.0,7811.507099,24419.297665,36.4,483.900,1313.65,4667.875,271143.6
TAC1179_6month,1310.0,9176.435115,29463.731620,49.1,516.000,1436.10,5272.750,363298.1
TAC1225_6month,1310.0,7849.027863,25033.442946,59.8,503.150,1435.40,4480.550,289001.7
TAC1174_Baseline,1310.0,7588.575878,24885.741892,46.8,515.950,1348.50,4626.175,304001.9
TAC1209_6month,1310.0,7876.510076,25277.701816,41.3,491.375,1376.65,4480.775,279286.8

===== SAMPLE MATRIX =====

HEAD:

,Patient_ID,SampleId,PercentDilution,SampleNotes,SampleDescription,TimePoint,SampleGroup,SiteId,HybControlNormScale,RowCheck,...,HEIGHT,WEIGHT,ALCOHOL_Y_N,CURENT SMOKER,Symp_Duration,Initial.Score,Final.Score,Erosive,Hep B serology wk 9 (IU/mL),vaccine centre
0,TAC1145,TAC1145_Baseline,40,NaN,EDTA-Plasma,Baseline,RA-nonresp,JRD,0.998,PASS,...,157,85.0,Yes ...,Yes,83.0,39,39,1,NaN,NaN
1,TAC1075,TAC1075_6month,40,NaN,EDTA-Plasma,6month,RA-responder,Newcastle,0.974,PASS,...,173,87.0,Yes ...,Yes,123.0,11,11,1,NaN,NaN
2,TAC1000,TAC1000_Baseline,40,NaN,EDTA-Plasma,Baseline,RA-responder,Newcastle,0.971,PASS,...,161,65.2,Yes ...,Yes,113.0,0,1,0,NaN,NaN
3,TAC1058,TAC1058_Baseline,40,NaN,EDTA-Plasma,Baseline,RA-nonresp,Newcastle,1.000,PASS,...,165,109.0,No ...,Yes,112.0,4,NaN,0,NaN,NaN
4,TAC1150,TAC1150_Baseline,40,NaN,EDTA-Plasma,Baseline,RA-nonresp,JRD,0.954,PASS,...,ND,60.9,Yes ...,No,165.0,1,1,0,NaN,NaN

SHAPE:
(237, 73)

DTYPES:
Patient_ID                        str
SampleId                          str
PercentDilution                 int64
SampleNotes                       str
SampleDescription                 str
                                ...
Initial.Score                  object
Final.Score                    object
Erosive                        object
Hep B serology wk 9 (IU/mL)    object
vaccine centre                    str
Length: 73, dtype: object

MISSING VALUES (top 10):
SampleNotes                    233
Hep B serology wk 9 (IU/mL)    209
vaccine centre                 197
Final.Score                     57
CRP.9M                          42
DAS28.9M                        40
DAS28.12M                       40
DAS28.18M                       40
ACPA.POSITIVE                   40
TOTAL.TENDER.6M                 40
dtype: int64

DTYPES (sample 20):
Patient_ID                 str
SampleId                   str
PercentDilution          int64
SampleNotes                str
SampleDescription          str
TimePoint                  str
SampleGroup                str
SiteId                     str
HybControlNormScale    float64
RowCheck                   str
NormScale_1            float64
NormScale_40           float64
NormScale_0_005        float64
Digest                     str
Study                      str
IM.STEROIDS.3MONTHS        str
ACPA.POSITIVE              str
RHUEMATOID.FACTOR          str
DAS28.0M               float64
DAS28.3M                object
dtype: object

SUMMARY STATISTICS (first 10 proteins):

,count,mean,std,min,25%,50%,75%,max
PercentDilution,237.0,40.000000,0.000000,40.000,40.000,40.000,40.000,40.000
HybControlNormScale,237.0,1.005211,0.059557,0.902,0.972,0.998,1.024,1.583
NormScale_1,237.0,1.012072,0.194736,0.493,0.876,1.006,1.135,1.698
NormScale_40,237.0,1.010899,0.193517,0.380,0.874,1.028,1.132,1.560
NormScale_0_005,237.0,1.011000,0.162578,0.580,0.896,1.004,1.109,1.746
DAS28.0M,197.0,5.567310,1.307324,2.230,4.720,5.760,6.350,8.680
DAS28.6M,197.0,3.352843,1.660047,0.280,2.070,3.300,4.540,7.320
HB.0M,197.0,105.193909,48.799677,10.900,99.000,126.000,137.000,170.000
LYMPHOCYTES.0M,197.0,1.889746,0.645393,0.410,1.570,1.800,2.200,5.400
MONOCYTES.0M,197.0,0.563553,0.204360,0.060,0.400,0.500,0.700,1.200