# Proteomics
Extract timepoints from dataset and create two new datasets from it
Creates new *mid_processing_datasets* folder and parquet files during runtime
Drops high corellating features and saves final output to *cleaned_datasets*

In [12]:
from src.common_imports import *
from src.data_audit import data_audit
from src.somascan import *
from src.save_wrapper import save_report
from src.extraction import extract_dtypes
from src.check_data import *
from src.normalization import *
from src.low_variance_report import low_variance_report
from src.featsel import run_correlation_selection

In [13]:
data = load()

Loading somascan...
Done loading!

In [14]:
print("Indexing data...")
df_exp = data['df_expMatrix']
df_samp = data['df_sampMatrix']
print("Done!")

Indexing data...
Done!

# Data and low variance reports
Shows an overview of the following
data_audit:
-   Dataframe shape ( rows x columns)
-   Duplicates
-   Missing Values
-   Numeric Features
-   Outliers by IQR and 3σ(68-95-99.7)
-   Categorical Consistency
-   Cleaning Summary

low_variance_report:
-   Total numeric features
-   predefined low_variance_threshold
-   low variance features found

In [15]:
# data analysis of raw data
save_report(data_audit, df_exp, "expression matrix")
save_report(data_audit,df_samp, "sample matrix")
save_report(low_variance_report, df_exp, "expression matrix")
save_report(low_variance_report, df_samp, "sample matrix")

Saved: ../../reports/expression matrix_data_audit.txt
Saved: ../../reports/sample matrix_data_audit.txt
Saved: ../../reports/expression matrix_low_variance_report.txt
Saved: ../../reports/sample matrix_low_variance_report.txt

# Extracting and saving
After taking a look at the data we extract them by timepoint
and split into two new datasets
additionally we create a pseudo glossary for if one wants to lookup the gene

In [16]:
# save splits
splits = reshape_and_split(df_exp, df_samp)

# save splits
save_splits(splits)

# create glossary
create_gene_lookup(df_exp)

Timepoints found: ['6month', 'Baseline']
  6month: (97, 1311)
  Baseline: (140, 1311)
Saved: ../../mid_processing_datasets/expression_matrix_6month.parquet
Saved: ../../mid_processing_datasets/expression_matrix_baseline.parquet
Saved: ../../mid_processing_datasets/gene_lookup.parquet

,EntrezGeneSymbol,EntrezGeneID,Target,TargetFullName,UniProt
SeqId,,,,,
2597-8_3,VEGFA,7422,VEGF,Vascular endothelial growth factor A,P15692
2654-19_1,TNFRSF1A,7132,TNF sR-I,Tumor necrosis factor receptor superfamily mem...,P19438
2788-55_1,MMP3,4314,MMP-3,Stromelysin-1,P08254
2967-8_1,VCAM1,7412,VCAM-1,Vascular cell adhesion protein 1,P19320
3046-31_1,RETN,56729,resistin,Resistin,Q9HD89
...,...,...,...,...,...
9211-19_3,SERPINF1,5176,PEDF,Pigment epithelium-derived factor,P36955
9212-22_3,CTSF,8722,CATF,Cathepsin F,Q9UBX1
9213-24_3,FTCD,10841,FTCD,Formimidoyltransferase-cyclodeaminase,O95954
9215-117_3,USP25,29761,UBP25,Ubiquitin carboxyl-terminal hydrolase 25,Q9UHP3
9216-100_3,PLXNB2,23654,PLXB2,Plexin-B2,O15031

# Verifiying
After saving the files we verify it by pulling from the new source
and running the data_audit and low_variance_report on them

In [17]:
# pulling saved data
df_exp_bl = pd.read_parquet("../../mid_processing_datasets/expression_matrix_baseline.parquet")
df_exp_6m = pd.read_parquet("../../mid_processing_datasets/expression_matrix_6month.parquet")
print("done reading")

done reading

In [18]:
# running data audit on newly formed data
save_report(data_audit, df_exp_bl, "baseline expression matrix")
save_report(data_audit, df_exp_6m, "6 months expression matrix")
save_report(low_variance_report,df_exp_bl, "baseline expression matrix")
save_report(low_variance_report, df_exp_6m, "6 months expression matrix")

Saved: ../../reports/baseline expression matrix_data_audit.txt
Saved: ../../reports/6 months expression matrix_data_audit.txt
Saved: ../../reports/baseline expression matrix_low_variance_report.txt
Saved: ../../reports/6 months expression matrix_low_variance_report.txt

In [19]:
# further sample verificiation
display(df_exp_bl.head())
display(df_exp_6m.head())

SeqId,Patient_ID,2597-8_3,2654-19_1,2788-55_1,2967-8_1,3046-31_1,4336-2_1,4337-49_2,4673-13_2,4867-15_2,...,9199-6_3,9201-13_3,9202-309_3,9204-33_3,9207-60_3,9211-19_3,9212-22_3,9213-24_3,9215-117_3,9216-100_3
SampleId,,,,,,,,,,,,,,,,,,,,,
TAC1145_BL,TAC1145,16301.7,1628.1,689.4,12386.8,1732.7,2461.5,146207.9,559.6,1556.6,...,7101.8,2950.0,1894.1,636.1,3068.7,63197.8,2521.2,7522.2,1114.9,4627.6
TAC1000_BL,TAC1000,10421.1,1220.8,426.4,11669.8,1042.4,1676.3,157654.1,787.4,512.5,...,5669.6,7869.2,7685.5,489.2,1507.6,57489.0,2201.4,6938.8,804.8,4887.5
TAC1058_BL,TAC1058,9352.7,1337.1,668.6,15387.8,2402.8,1377.1,142311.8,225.7,499.3,...,6163.6,2828.3,2822.8,645.4,2429.1,53653.8,1937.3,14913.5,1242.0,4860.3
TAC1150_BL,TAC1150,11279.3,1355.2,390.8,12320.6,1350.4,216.0,41350.3,266.6,541.4,...,5003.9,3559.3,13755.8,987.8,5549.8,53542.5,2049.0,24307.1,683.9,4903.5
TAC1174_BL,TAC1174,10622.2,1062.2,671.9,16307.8,1323.5,418.5,87174.8,232.8,429.1,...,8339.7,3676.7,1498.4,779.9,2497.6,55372.4,2975.7,14636.7,925.1,7282.2

SeqId,Patient_ID,2597-8_3,2654-19_1,2788-55_1,2967-8_1,3046-31_1,4336-2_1,4337-49_2,4673-13_2,4867-15_2,...,9199-6_3,9201-13_3,9202-309_3,9204-33_3,9207-60_3,9211-19_3,9212-22_3,9213-24_3,9215-117_3,9216-100_3
SampleId,,,,,,,,,,,,,,,,,,,,,
TAC1075_M6,TAC1075,11993.7,1358.4,585.6,14119.3,997.0,2150.9,81794.4,512.9,633.8,...,3776.1,2515.1,1780.4,1248.7,1799.0,55797.4,2078.4,9340.3,1061.8,5881.7
TAC1148_M6,TAC1148,11000.8,1087.1,602.3,13485.6,1186.2,342.0,16741.7,222.5,417.4,...,4251.7,3025.8,1769.1,500.5,3253.0,59882.3,2515.2,10679.1,913.7,5373.4
TAC1179_M6,TAC1179,15116.4,1205.6,382.9,13505.8,1155.5,413.7,116629.2,383.2,1135.1,...,10580.8,5813.3,3905.4,568.0,1714.8,61199.4,1863.4,3418.3,780.7,4142.3
TAC1225_M6,TAC1225,12873.1,2062.8,1243.5,20003.1,1864.4,301.3,119197.3,274.8,398.6,...,6877.5,3461.2,3426.8,668.2,2726.7,72002.7,2514.8,13206.6,699.5,5775.7
TAC1209_M6,TAC1209,10796.4,1178.1,1136.9,15152.3,1364.6,863.3,131055.7,273.4,435.8,...,4859.8,3049.0,1912.6,515.5,2130.7,56690.5,2221.6,12061.3,887.9,4544.7

In [20]:
extract_dtypes(df_exp_bl, verbose=True)

Schema of total values
(column, row)
Absolute Values: (140, 1311)
['Patient_ID', '2597-8_3', '2654-19_1', '2788-55_1', '2967-8_1', '3046-31_1', '4336-2_1', '4337-49_2', '4673-13_2', '4867-15_2', '4924-32_1', '5509-7_3', '8484-24_3', '10336-3_3', '10337-83_3', '10339-48_3', '10342-55_3', '10344-334_3', '10346-5_3', '10351-51_3', '10356-21_3', '10358-33_3', '10361-25_3', '10362-35_3', '10363-13_3', '10364-6_3', '10365-132_3', '10366-11_3', '10367-62_3', '10370-21_3', '10372-18_3', '10990-21_3', '11067-13_3', '11071-1_3', '11081-1_3', '11089-7_3', '11094-104_3', '11096-57_3', '11098-1_3', '11101-18_3', '11102-22_3', '11103-24_3', '11104-13_3', '11105-171_3', '11510-31_3', '11513-92_3', '11514-196_3', '11516-7_3', '12060-28_3', '13088-397_3', '13089-6_3', '13090-17_3', '13093-6_3', '13094-75_3', '13095-51_3', '13097-11_3', '13098-93_3', '13101-60_3', '13102-1_3', '13103-125_3', '13104-32_3', '13105-7_3', '13107-9_3', '13109-82_3', '13111-79_3', '13112-179_3', '13113-7_3', '13114-50_3', '13116-25_3', '13117-232_3', '13118-5_3', '13119-26_3', '13122-19_3', '13123-3_3', '13124-20_3', '13125-45_3', '13126-52_3', '13129-40_3', '13130-150_3', '13131-5_3', '13132-14_3', '13133-73_3', '14114-18_3', '14115-34_3', '14116-129_3', '14120-2_3', '14121-24_3', '14122-132_3', '14123-34_3', '14124-6_3', '14125-5_3', '14127-240_3', '14128-121_3', '14129-1_3', '14131-37_3', '14132-21_3', '14133-93_3', '14134-49_3', '14135-3_3', '14136-234_3', '14139-16_3', '14143-8_3', '14144-3_3', '14146-92_3', '14147-50_3', '14149-9_3', '14150-7_3', '14151-4_3', '14153-8_3', '14156-33_3', '14157-21_3', '14158-17_3', '14583-49_3', '2182-54_1', '2190-55_1', '2192-63_10', '2201-17_6', '2211-9_6', '2212-69_1', '2247-20_11', '2278-61_4', '2333-72_1', '2358-19_2', '2381-52_4', '2418-55_9', '2421-7_3', '2429-27_4', '2431-17_3', '2436-49_4', '2441-2_4', '2443-10_4', '2447-7_4', '2449-1_4', '2468-62_3', '2474-54_5', '2475-1_3', '2480-58_3', '2500-2_3', '2501-51_3', '2505-49_3', '2514-65_3', '2515-14_3', '2516-57_3', '2524-56_3', '2526-53_3', '2558-51_3', '2567-5_6', '2571-12_3', '2578-67_2', '2579-17_5', '2580-83_2', '2585-2_5', '2598-9_3', '2599-51_2', '2602-2_2', '2603-61_2', '2605-49_2', '2607-54_2', '2609-59_2', '2611-72_2', '2612-5_2', '2614-28_2', '2615-60_2', '2616-23_18', '2617-56_35', '2618-10_2', '2619-72_2', '2620-4_2', '2622-18_1', '2623-54_4', '2624-31_2', '2625-53_4', '2630-12_2', '2631-50_2', '2632-5_2', '2633-52_2', '2634-2_2', '2635-61_2', '2636-10_2', '2637-77_2', '2638-12_2', '2640-3_2', '2642-4_1', '2643-57_2', '2644-11_2', '2645-54_1', '2647-66_2', '2649-77_2', '2652-15_1', '2658-27_1', '2665-26_2', '2666-53_2', '2668-70_2', '2670-67_4', '2677-1_1', '2681-23_2', '2682-68_1', '2683-1_2', '2685-21_2', '2686-67_2', '2687-2_1', '2692-74_2', '2693-20_3', '2695-25_1', '2696-87_2', '2697-7_2', '2700-56_2', '2704-74_1', '2705-5_2', '2706-69_2', '2708-54_2', '2711-6_2', '2714-78_2', '2715-25_2', '2719-3_4', '2723-9_2', '2728-62_2', '2730-58_2', '2731-29_2', '2732-58_3', '2734-49_4', '2737-22_2', '2741-22_2', '2742-68_2', '2743-5_2', '2744-57_2', '2746-56_1', '2747-3_2', '2748-3_2', '2750-3_2', '2751-16_2', '2752-62_2', '2753-2_2', '2754-50_2', '2755-8_2', '2760-2_2', '2761-49_2', '2762-30_2', '2763-66_2', '2764-20_2', '2765-4_3', '2768-56_2', '2769-3_2', '2770-51_2', '2771-35_2', '2773-50_2', '2774-10_3', '2775-54_2', '2778-10_2', '2780-35_2', '2781-63_2', '2783-18_2', '2785-15_2', '2789-26_2', '2790-54_2', '2794-60_2', '2795-23_3', '2796-62_2', '2797-56_2', '2805-6_2', '2806-49_2', '2809-25_2', '2811-27_1', '2813-11_2', '2816-50_2', '2819-23_2', '2822-56_2', '2823-7_1', '2826-53_2', '2827-23_2', '2828-82_2', '2829-19_2', '2831-29_1', '2833-20_1', '2834-54_1', '2835-1_4', '2836-68_2', '2837-3_2', '2838-53_1', '2839-2_1', '2841-13_2', '2843-13_2', '2844-53_2', '2846-24_2', '2848-2_2', '2849-49_1', '2851-63_3', '2853-68_2', '2855-49_2', '2857-70_2', '2858-29_2', '2859-69_2', '2860-19_2', '2864-2_3', '2865-77_2', '2869-68_3', '2870-29_2', '2871-73_2', '2875-15_2', '2876-74_2', '2877-3_1', '2878-66_2', '2879-9_2', '2888-49_2', '2889-37_2', '2890-59_2', '2891-1_3', '2900-53_3', '2906-55_3', '2911-27_2', '2913-1_2', '2915-6_2', '2917-3_2', '2925-9_1', '2937-10_2', '2938-55_2', '2939-10_2', '2942-50_2', '2943-5_2', '2944-66_2', '2945-25_1', '2946-52_2', '2948-58_2', '2949-6_2', '2950-57_2', '2952-75_2', '2953-31_2', '2960-66_2', '2961-1_2', '2962-50_2', '2966-65_2', '2968-61_1', '2969-11_1', '2970-60_2', '2972-57_2', '2973-15_2', '2974-61_2', '2975-19_2', '2976-58_2', '2977-7_2', '2979-8_2', '2981-9_3', '2982-82_2', '2985-35_1', '2986-49_2', '2987-37_3', '2988-57_2', '2991-9_2', '2992-59_2', '2993-1_2', '2994-71_2', '2997-8_1', '2998-53_2', '2999-6_2', '3000-66_1', '3003-29_2', '3004-67_2', '3005-5_2', '3007-7_2', '3009-3_2', '3010-53_2', '3022-4_2', '3024-18_2', '3025-50_1', '3026-5_2', '3028-36_2', '3029-52_2', '3030-3_2', '3032-11_2', '3033-57_1', '3034-1_2', '3035-80_2', '3037-62_1', '3038-9_2', '3040-59_1', '3041-55_2', '3042-7_2', '3043-49_2', '3044-3_2', '3045-72_2', '3049-61_2', '3050-7_2', '3052-8_2', '3053-49_2', '3054-3_2', '3055-54_2', '3056-11_1', '3057-55_1', '3059-50_2', '3060-43_2', '3061-61_2', '3065-65_1', '3066-12_1', '3067-67_1', '3069-52_3', '3070-1_2', '3072-4_2', '3073-51_2', '3074-6_2', '3077-66_2', '3078-1_2', '3079-62_2', '3081-70_2', '3082-9_2', '3083-71_1', '3091-70_2', '3115-64_2', '3122-6_2', '3132-1_1', '3143-3_1', '3151-6_1', '3152-57_1', '3166-92_1', '3168-8_2', '3169-70_2', '3170-6_1', '3171-57_2', '3172-28_2', '3173-49_2', '3174-2_1', '3175-51_5', '3177-49_2', '3178-5_2', '3179-51_2', '3181-50_2', '3182-38_2', '3184-25_2', '3186-2_2', '3187-52_2', '3189-61_2', '3191-50_2', '3192-3_2', '3194-36_2', '3195-50_2', '3196-6_2', '3197-70_2', '3198-4_1', '3199-54_2', '3200-49_2', '3201-49_2', '3202-28_2', '3204-2_2', '3206-4_2', '3208-2_4', '3209-69_1', '3210-1_2', '3212-30_3', '3213-65_2', '3216-2_2', '3217-74_2', '3220-40_2', '3221-54_1', '3222-11_2', '3232-28_2', '3234-23_2', '3235-50_2', '3280-49_2', '3281-19_1', '3283-21_1', '3284-75_1', '3285-23_2', '3289-19_2', '3290-50_2', '3291-30_2', '3292-75_1', '3293-2_4', '3294-55_2', '3296-92_2', '3298-52_2', '3299-29_2', '3302-58_1', '3303-23_2', '3305-6_1', '3309-2_2', '3310-62_1', '3311-27_1', '3312-64_1', '3313-21_2', '3314-74_2', '3315-15_1', '3316-58_1', '3317-33_1', '3320-49_2', '3321-2_2', '3322-52_2', '3323-37_1', '3324-51_1', '3325-2_2', '3326-58_2', '3327-27_1', '3329-14_2', '3331-8_1', '3332-57_1', '3336-50_1', '3339-33_1', '3340-53_1', '3341-33_4', '3343-1_4', '3344-60_4', '3346-72_2', '3347-9_2', '3348-49_2', '3350-53_2', '3351-1_1', '3352-80_3', '3356-50_1', '3357-67_2', '3358-51_2', '3359-11_2', '3360-50_4', '3361-26_2', '3362-61_2', '3363-31_4', '3364-76_2', '3365-7_2', '3366-51_2', '3367-8_3', '3373-5_2', '3374-49_2', '3376-49_2', '3378-49_2', '3379-29_1', '3381-24_2', '3387-1_2', '3388-58_2', '3389-7_2', '3390-72_2', '3391-10_2', '3392-68_2', '3394-81_2', '3396-54_2', '3397-7_4', '3399-31_2', '3400-49_2', '3401-8_2', '3403-1_2', '3404-51_2', '3405-6_2', '3412-7_1', '3413-50_2', '3414-40_2', '3415-61_2', '3416-2_2', '3418-12_2', '3419-49_2', '3420-21_2', '3421-54_2', '3422-4_2', '3423-59_2', '3427-63_2', '3431-54_2', '3432-21_2', '3434-34_1', '3435-53_2', '3437-80_3', '3438-10_2', '3440-7_2', '3441-64_2', '3443-61_2', '3445-53_2', '3446-7_2', '3447-64_2', '3448-13_2', '3449-58_2', '3450-4_2', '3452-17_2', '3453-87_2', '3457-57_1', '3459-49_2', '3461-58_1', '3466-8_2', '3469-74_1', '3470-1_2', '3471-49_1', '3472-40_2', '3473-78_2', '3474-19_2', '3477-63_2', '3479-71_2', '3480-7_1', '3481-87_1', '3484-60_2', '3485-28_2', '3486-58_2', '3487-32_2', '3488-64_2', '3489-9_2', '3494-71_3', '3495-15_2', '3497-13_2', '3499-77_2', '3503-4_2', '3504-58_2', '3505-6_2', '3506-49_1', '3508-78_3', '3509-1_1', '3514-49_2', '3516-60_2', '3518-54_2', '3519-3_2', '3520-58_1', '3521-16_2', '3522-57_1', '3534-14_2', '3535-84_1', '3538-26_1', '3554-24_1', '3580-25_8', '3581-53_3', '3583-54_4', '3585-54_4', '3587-53_2', '3590-8_3', '3591-51_3', '3592-4_3', '3593-72_3', '3594-6_5', '3600-2_3', '3601-54_3', '3603-60_5', '3605-77_4', '3606-2_5', '3607-71_1', '3608-12_5', '3611-70_4', '3612-6_4', '3613-62_5', '3616-3_5', '3617-80_4', '3620-67_2', '3622-33_4', '3623-84_4', '3624-3_4', '3627-71_4', '3628-3_4', '3629-60_4', '3630-27_4', '3633-70_5', '3634-5_4', '3635-76_4', '3636-37_4', '3640-14_3', '3642-4_1', '3643-90_2', '3644-5_4', '3646-7_4', '3647-49_4', '3651-50_5', '3654-27_5', '3656-9_1', '3657-74_3', '3666-17_4', '3676-15_3', '3681-87_3', '3684-78_3', '3685-53_1', '3707-12_2', '3708-62_1', '3709-4_2', '3710-49_2', '3714-49_2', '3719-2_2', '3723-1_2', '3727-35_1', '3728-52_2', '3730-81_2', '3738-54_4', '3758-68_3', '3761-4_2', '3766-51_4', '3773-15_4', '3795-6_2', '3796-79_2', '3797-1_1', '3798-71_1', '3799-11_2', '3800-71_2', '3802-50_1', '3803-10_2', '3805-16_2', '3806-55_1', '3807-1_2', '3808-76_2', '3809-1_2', '3810-50_2', '3813-3_2', '3815-14_1', '3817-18_1', '3820-68_2', '3821-28_1', '3822-54_2', '3823-9_1', '3825-18_2', '3827-22_1', '3828-54_2', '3831-21_1', '3832-51_1', '3835-11_2', '3836-51_2', '3839-60_2', '3844-2_1', '3845-51_2', '3847-56_2', '3848-14_2', '3852-19_2', '3853-56_1', '3854-24_1', '3855-56_1', '3858-5_1', '3859-50_2', '3860-7_2', '3864-5_2', '3865-53_1', '3866-7_2', '3867-49_1', '3868-8_1', '3872-2_1', '3873-51_2', '3874-8_1', '3875-62_1', '3877-67_2', '3879-50_1', '3881-49_2', '3887-90_2', '3888-8_1', '3889-64_2', '3890-8_2', '3891-56_1', '3893-64_1', '3894-15_2', '3896-5_2', '3897-61_1', '3898-5_2', '3902-21_2', '3903-49_2', '3905-62_1', '4122-12_2', '4123-60_2', '4124-24_2', '4125-52_2', '4126-22_1', '4127-75_1', '4128-27_2', '4129-72_1', '4130-71_1', '4131-72_2', '4132-27_2', '4133-54_2', '4134-4_2', '4135-84_2', '4136-40_2', '4137-57_2', '4138-25_2', '4139-71_2', '4140-3_2', '4141-79_1', '4143-74_2', '4144-13_1', '4145-58_2', '4146-58_2', '4148-49_2', '4149-8_2', '4150-75_2', '4151-6_2', '4152-58_2', '4153-11_2', '4154-57_2', '4155-3_2', '4156-74_1', '4157-2_1', '4158-54_2', '4159-130_1', '4160-49_1', '4162-54_2', '4163-5_2', '4165-2_1', '4179-57_3', '4184-43_3', '4187-49_2', '4188-1_2', '4192-10_2', '4194-26_3', '4203-50_2', '4209-60_2', '4212-5_3', '4217-49_3', '4220-39_2', '4224-7_2', '4230-1_2', '4232-19_2', '4234-8_2', '4237-70_3', '4238-4_2', '4240-31_2', '4245-80_2', '4246-40_2', '4249-64_2', '4250-23_3', '4254-6_2', '4258-15_2', '4261-55_2', '4267-81_3', '4271-75_2', '4272-46_2', '4276-10_2', '4278-14_3', '4280-47_2', '4282-3_2', '4284-18_3', '4292-5_3', '4294-16_2', '4297-62_3', '4301-58_2', '4304-18_2', '4306-4_2', '4309-59_3', '4314-12_2', '4318-12_3', '4322-28_3', '4324-33_2', '4328-2_2', '4332-6_2', '4342-10_3', '4355-13_1', '4359-87_1', '4374-45_2', '4389-2_1', '4392-54_2', '4393-3_1', '4394-71_2', '4396-54_1', '4397-26_2', '4407-10_1', '4413-3_2', '4414-69_2', '4420-7_2', '4423-77_2', '4428-1_2', '4429-51_2', '4430-44_3', '4435-66_2', '4436-1_2', '4437-56_3', '4440-15_2', '4449-67_3', '4450-26_2', '4452-9_2', '4453-83_3', '4455-89_2', '4459-68_2', '4460-8_2', '4464-10_2', '4467-49_2', '4468-21_2', '4469-78_2', '4471-50_2', '4472-5_2', '4474-19_2', '4476-22_2', '4479-14_2', '4480-59_2', '4481-34_2', '4482-66_2', '4487-1_1', '4490-65_2', '4491-4_2', '4493-92_1', '4495-33_2', '4496-60_2', '4498-62_2', '4499-21_1', '4500-50_2', '4533-76_2', '4534-10_2', '4535-50_2', '4540-11_2', '4541-49_2', '4542-24_2', '4543-65_2', '4544-4_3', '4545-53_3', '4546-27_3', '4547-59_2', '4548-4_2', '4549-78_2', '4551-72_3', '4553-65_3', '4556-10_2', '4557-61_2', '4559-64_2', '4561-65_2', '4562-1_2', '4563-61_2', '4564-2_2', '4566-24_3', '4567-82_2', '4568-17_2', '4569-52_2', '4588-1_2', '4693-72_2', '4697-59_2', '4703-87_2', '4706-17_2', '4708-3_2', '4712-28_2', '4717-55_2', '4718-5_2', '4719-58_2', '4721-54_2', '4763-31_3', '4769-10_3', '4771-10_3', '4774-62_3', '4775-34_3', '4785-30_3', '4786-58_3', '4792-51_2', '4801-13_3', '4807-13_3', '4811-33_3', '4815-25_3', '4829-43_6', '4831-4_2', '4832-75_2', '4834-61_2', '4840-73_1', '4842-62_2', '4851-25_1', '4859-6_1', '4862-63_1', '4866-59_2', '4874-3_1', '4876-32_1', '4878-3_1', '4880-21_1', '4883-56_2', '4886-3_1', '4889-82_1', '4890-10_1', '4891-50_1', '4900-8_1', '4903-72_1', '4904-7_1', '4905-63_1', '4906-35_1', '4907-56_1', '4908-6_1', '4909-68_1', '4910-21_1', '4911-49_2', '4912-17_1', '4913-78_1', '4914-10_1', '4915-64_2', '4916-2_1', '4917-62_1', '4920-10_1', '4922-13_1', '4923-79_1', '4925-54_2', '4929-55_1', '4930-21_1', '4931-59_1', '4956-2_1', '4957-1_2', '4959-2_1', '4960-72_1', '4961-17_1', '4962-52_1', '4963-19_1', '4964-67_1', '4965-27_1', '4967-1_1', '4968-50_1', '4969-2_1', '4970-55_1', '4971-1_1', '4973-18_1', '4976-57_1', '4978-54_2', '4979-34_2', '4981-6_1', '4982-54_1', '4983-6_1', '4984-83_1', '4985-11_1', '4986-59_1', '4987-17_1', '4988-49_2', '4989-7_1', '4990-87_1', '4991-12_1', '4992-49_1', '4993-16_1', '4994-178_1', '4995-16_1', '4996-66_1', '4997-19_1', '4998-50_2', '5000-52_1', '5001-6_2', '5002-76_1', '5004-69_1', '5005-4_1', '5006-71_1', '5007-1_1', '5008-51_1', '5009-11_1', '5011-11_1', '5012-67_1', '5013-2_1', '5014-49_1', '5015-15_1', '5016-61_2', '5017-19_1', '5018-68_1', '5019-16_2', '5020-50_1', '5021-13_1', '5023-23_1', '5024-67_1', '5026-66_1', '5028-59_1', '5029-3_1', '5030-52_1', '5031-10_1', '5032-64_1', '5033-27_1', '5034-79_1', '5035-7_1', '5036-50_1', '5060-62_3', '5061-27_3', '5062-60_3', '5063-12_2', '5065-8_2', '5066-134_3', '5068-54_3', '5069-9_3', '5070-76_3', '5071-3_3', '5073-30_2', '5076-53_2', '5077-28_3', '5078-82_3', '5080-131_3', '5082-51_3', '5084-154_3', '5085-18_3', '5087-5_3', '5088-175_3', '5089-11_3', '5090-49_2', '5091-28_3', '5092-51_3', '5093-47_3', '5094-62_3', '5095-21_3', '5096-51_3', '5097-14_3', '5098-79_3', '5099-14_3', '5100-53_3', '5102-55_3', '5103-30_3', '5104-57_3', '5105-2_3', '5106-52_3', '5107-7_2', '5108-72_3', '5109-24_3', '5110-84_3', '5111-15_3', '5112-73_3', '5114-65_3', '5115-31_3', '5116-62_2', '5117-14_3', '5118-74_2', '5121-3_2', '5122-92_2', '5124-69_3', '5125-6_3', '5128-53_3', '5129-12_3', '5130-67_3', '5131-15_3', '5132-71_3', '5133-17_3', '5134-52_2', '5138-50_3', '5139-32_3', '5140-56_3', '5178-5_3', '5183-53_3', '5193-51_3', '5196-7_3', '5201-50_4', '5202-4_3', '5204-13_3', '5223-59_3', '5225-50_3', '5226-36_3', '5227-60_3', '5228-25_2', '5229-90_3', '5230-99_3', '5231-79_3', '5236-2_3', '5238-26_3', '5242-37_3', '5244-12_3', '5245-40_5', '5246-64_3', '5248-68_2', '5249-31_3', '5250-53_3', '5252-33_3', '5253-1_1', '5254-69_3', '5255-22_3', '5256-86_3', '5259-2_3', '5260-80_3', '5261-13_3', '5262-57_3', '5264-65_3', '5265-12_3', '5268-49_3', '5271-5_1', '5272-55_2', '5275-28_2', '5280-68_5', '5301-7_3', '5307-12_3', '5308-89_2', '5312-49_3', '5315-22_3', '5316-54_3', '5328-33_37', '5335-73_3', '5337-64_3', '5339-49_3', '5340-24_3', '5343-74_3', '5345-51_3', '5346-24_3', '5347-59_3', '5349-69_3', '5350-14_2', '5351-52_3', '5352-11_3', '5353-89_2', '5354-11_3', '5355-69_3', '5356-2_3', '5357-60_3', '5358-3_3', '5359-65_3', '5360-9_2', '5363-51_3', '5364-7_3', '5383-14_3', '5384-67_3', '5392-73_2', '5400-52_3', '5404-53_3', '5410-53_3', '5412-53_3', '5424-55_3', '5430-66_3', '5437-63_3', '5440-26_3', '5441-67_3', '5443-62_2', '5451-1_3', '5452-71_3', '5456-59_2', '5457-5_2', '5459-33_3', '5460-60_3', '5462-62_3', '5463-22_3', '5464-52_3', '5465-32_3', '5467-15_3', '5468-67_3', '5470-69_2', '5475-10_3', '5476-66_3', '5478-50_2', '5480-49_3', '5481-16_3', '5482-61_3', '5483-1_3', '5484-63_3', '5486-73_3', '5487-7_3', '5488-74_3', '5489-18_3', '5490-53_3', '5491-12_3', '5493-17_3', '5494-52_3', '5508-62_3', '5526-53_3', '5532-53_3', '5534-49_2', '5542-22_2', '5792-8_2', '5798-3_3', '5801-72_3', '5803-24_3', '5807-77_3', '5810-25_3', '5813-58_3', '5822-22_3', '5825-49_3', '5834-18_3', '5837-49_3', '5843-60_3', '5846-24_3', '5852-6_3', '5854-60_3', '5858-6_5', '5861-78_3', '5864-10_3', '5867-60_3', '5870-23_2', '5879-51_3', '5882-34_2', '5885-55_3', '5888-29_3', '5897-58_3', '5900-11_2', '5903-91_2', '5909-51_3', '5915-58_3', '5918-5_3', '5921-58_3', '5927-4_3', '5934-1_3', '5936-53_3', '5939-42_3', '5947-90_3', '5954-62_3', '5957-30_3', '6151-18_3', '6152-111_3', '6641-60_3', '6647-55_3', '6649-51_3', '6653-58_3', '7624-19_3', '7625-27_3', '7628-40_3', '7638-30_3', '7640-29_3', '7648-9_3', '7655-11_3', '7660-21_3', '8446-4_3', '8447-11_3', '8450-36_3', '8458-111_3', '8459-10_3', '8462-18_3', '8463-2_3', '8464-31_3', '8465-52_3', '8467-9_3', '8468-19_3', '8469-41_3', '8470-213_3', '8474-6_3', '8476-11_3', '8479-4_3', '8480-29_3', '8485-7_3', '8488-33_3', '9168-31_3', '9169-14_3', '9170-24_3', '9171-11_3', '9172-69_3', '9173-21_3', '9175-48_3', '9176-3_3', '9177-6_3', '9178-30_3', '9180-6_3', '9182-3_3', '9183-7_3', '9185-15_3', '9187-2_3', '9188-119_3', '9190-7_3', '9191-8_3', '9196-8_3', '9197-4_3', '9199-6_3', '9201-13_3', '9202-309_3', '9204-33_3', '9207-60_3', '9211-19_3', '9212-22_3', '9213-24_3', '9215-117_3', '9216-100_3']
Numerical Values: (140, 1310)

(SeqId      Patient_ID  2597-8_3  2654-19_1  2788-55_1  2967-8_1  3046-31_1  \
 SampleId
 TAC1145_BL    TAC1145   16301.7     1628.1      689.4   12386.8     1732.7
 TAC1000_BL    TAC1000   10421.1     1220.8      426.4   11669.8     1042.4
 TAC1058_BL    TAC1058    9352.7     1337.1      668.6   15387.8     2402.8
 TAC1150_BL    TAC1150   11279.3     1355.2      390.8   12320.6     1350.4
 TAC1174_BL    TAC1174   10622.2     1062.2      671.9   16307.8     1323.5
 ...               ...       ...        ...        ...       ...        ...
 TAC1042_BL    TAC1042    9384.1      943.9      814.4   10377.0     2250.5
 TAC1232_BL    TAC1232   11154.9     1281.2     1889.8   17802.6     1633.2
 TAC1082_BL    TAC1082    6652.2     1636.0     1102.0   11790.8      979.0
 TAC1179_BL    TAC1179   16324.1     1614.3      601.3   15779.1     1683.5
 VAC2038_BL    VAC2038    7696.6     1052.6      740.3   10938.4     1233.0

 SeqId       4336-2_1  4337-49_2  4673-13_2  4867-15_2  ...  9199-6_3  \
 SampleId                                               ...
 TAC1145_BL    2461.5   146207.9      559.6     1556.6  ...    7101.8
 TAC1000_BL    1676.3   157654.1      787.4      512.5  ...    5669.6
 TAC1058_BL    1377.1   142311.8      225.7      499.3  ...    6163.6
 TAC1150_BL     216.0    41350.3      266.6      541.4  ...    5003.9
 TAC1174_BL     418.5    87174.8      232.8      429.1  ...    8339.7
 ...              ...        ...        ...        ...  ...       ...
 TAC1042_BL    1604.1   168041.4      390.0      582.6  ...    6390.7
 TAC1232_BL    2509.2   106927.8      676.0      607.3  ...    5062.3
 TAC1082_BL    8813.5    92119.4      195.4      980.7  ...    6730.9
 TAC1179_BL     872.9   157544.8      490.7     1247.4  ...   12071.1
 VAC2038_BL    6032.5    20577.7      239.6      435.0  ...    4858.7

 SeqId       9201-13_3  9202-309_3  9204-33_3  9207-60_3  9211-19_3  9212-22_3  \
 SampleId
 TAC1145_BL     2950.0      1894.1      636.1     3068.7    63197.8     2521.2
 TAC1000_BL     7869.2      7685.5      489.2     1507.6    57489.0     2201.4
 TAC1058_BL     2828.3      2822.8      645.4     2429.1    53653.8     1937.3
 TAC1150_BL     3559.3     13755.8      987.8     5549.8    53542.5     2049.0
 TAC1174_BL     3676.7      1498.4      779.9     2497.6    55372.4     2975.7
 ...               ...         ...        ...        ...        ...        ...
 TAC1042_BL     5209.1      7615.7      762.6     2473.0    55404.6     1635.9
 TAC1232_BL     3878.0     19389.6      390.1      877.2    44690.6     4918.2
 TAC1082_BL     3845.6      5016.3      708.1     2262.1    63573.6     2091.9
 TAC1179_BL     3357.0      1106.0      660.3     2140.2    49439.2     1602.6
 VAC2038_BL     3644.0      2620.5      663.9     3996.3    57319.5     3054.9

 SeqId       9213-24_3  9215-117_3  9216-100_3
 SampleId
 TAC1145_BL     7522.2      1114.9      4627.6
 TAC1000_BL     6938.8       804.8      4887.5
 TAC1058_BL    14913.5      1242.0      4860.3
 TAC1150_BL    24307.1       683.9      4903.5
 TAC1174_BL    14636.7       925.1      7282.2
 ...               ...         ...         ...
 TAC1042_BL    27503.5       853.7      4388.6
 TAC1232_BL    14205.2       996.6      6644.6
 TAC1082_BL    25993.3      3415.6      4202.4
 TAC1179_BL     2045.2       944.8      4605.7
 VAC2038_BL    15101.4       948.9      4504.2

 [140 rows x 1311 columns],
 SeqId       2597-8_3  2654-19_1  2788-55_1  2967-8_1  3046-31_1  4336-2_1  \
 SampleId
 TAC1145_BL   16301.7     1628.1      689.4   12386.8     1732.7    2461.5
 TAC1000_BL   10421.1     1220.8      426.4   11669.8     1042.4    1676.3
 TAC1058_BL    9352.7     1337.1      668.6   15387.8     2402.8    1377.1
 TAC1150_BL   11279.3     1355.2      390.8   12320.6     1350.4     216.0
 TAC1174_BL   10622.2     1062.2      671.9   16307.8     1323.5     418.5
 ...              ...        ...        ...       ...        ...       ...
 TAC1042_BL    9384.1      943.9      814.4   10377.0     2250.5    1604.1
 TAC1232_BL   11154.9     1281.2     1889.8   17802.6     1633.2    2509.2
 TAC1082_BL    6652.2     1636.0     1102.0   11790.8      979.0    8813.5
 TAC1179_BL   16324.1     1614.3      601.3   15779.1     1683.5     872.9
 VAC2038_BL    7696.6     1052.6      740.3   10938.4     1233.0    6032.5

 SeqId       4337-49_2  4673-13_2  4867-15_2  4924-32_1  ...  9199-6_3  \
 SampleId                                                ...
 TAC1145_BL   146207.9      559.6     1556.6     3055.8  ...    7101.8
 TAC1000_BL   157654.1      787.4      512.5      775.7  ...    5669.6
 TAC1058_BL   142311.8      225.7      499.3     1082.9  ...    6163.6
 TAC1150_BL    41350.3      266.6      541.4      639.9  ...    5003.9
 TAC1174_BL    87174.8      232.8      429.1      790.0  ...    8339.7
 ...               ...        ...        ...        ...  ...       ...
 TAC1042_BL   168041.4      390.0      582.6      970.9  ...    6390.7
 TAC1232_BL   106927.8      676.0      607.3     2804.5  ...    5062.3
 TAC1082_BL    92119.4      195.4      980.7      898.7  ...    6730.9
 TAC1179_BL   157544.8      490.7     1247.4     1286.8  ...   12071.1
 VAC2038_BL    20577.7      239.6      435.0      518.9  ...    4858.7

 SeqId       9201-13_3  9202-309_3  9204-33_3  9207-60_3  9211-19_3  9212-22_3  \
 SampleId
 TAC1145_BL     2950.0      1894.1      636.1     3068.7    63197.8     2521.2
 TAC1000_BL     7869.2      7685.5      489.2     1507.6    57489.0     2201.4
 TAC1058_BL     2828.3      2822.8      645.4     2429.1    53653.8     1937.3
 TAC1150_BL     3559.3     13755.8      987.8     5549.8    53542.5     2049.0
 TAC1174_BL     3676.7      1498.4      779.9     2497.6    55372.4     2975.7
 ...               ...         ...        ...        ...        ...        ...
 TAC1042_BL     5209.1      7615.7      762.6     2473.0    55404.6     1635.9
 TAC1232_BL     3878.0     19389.6      390.1      877.2    44690.6     4918.2
 TAC1082_BL     3845.6      5016.3      708.1     2262.1    63573.6     2091.9
 TAC1179_BL     3357.0      1106.0      660.3     2140.2    49439.2     1602.6
 VAC2038_BL     3644.0      2620.5      663.9     3996.3    57319.5     3054.9

 SeqId       9213-24_3  9215-117_3  9216-100_3
 SampleId
 TAC1145_BL     7522.2      1114.9      4627.6
 TAC1000_BL     6938.8       804.8      4887.5
 TAC1058_BL    14913.5      1242.0      4860.3
 TAC1150_BL    24307.1       683.9      4903.5
 TAC1174_BL    14636.7       925.1      7282.2
 ...               ...         ...         ...
 TAC1042_BL    27503.5       853.7      4388.6
 TAC1232_BL    14205.2       996.6      6644.6
 TAC1082_BL    25993.3      3415.6      4202.4
 TAC1179_BL     2045.2       944.8      4605.7
 VAC2038_BL    15101.4       948.9      4504.2

 [140 rows x 1310 columns],
 SeqId      Patient_ID
 SampleId
 TAC1145_BL    TAC1145
 TAC1000_BL    TAC1000
 TAC1058_BL    TAC1058
 TAC1150_BL    TAC1150
 TAC1174_BL    TAC1174
 ...               ...
 TAC1042_BL    TAC1042
 TAC1232_BL    TAC1232
 TAC1082_BL    TAC1082
 TAC1179_BL    TAC1179
 VAC2038_BL    VAC2038

 [140 rows x 1 columns],
 Empty DataFrame
 Columns: []
 Index: [TAC1145_BL, TAC1000_BL, TAC1058_BL, TAC1150_BL, TAC1174_BL, TAC1242_BL, VAC2042_BL, TAC1139_BL, VAC2005_BL, TAC1016_BL, TAC1184_BL, TAC1250_BL, TAC1125_BL, TAC1031_BL, TAC1171_BL, TAC1095_BL, TAC1072_BL, TAC1049_BL, TAC1208_BL, VAC2015_BL, VAC2000_BL, TAC1127_BL, TAC1003_BL, TAC1209_BL, TAC1008_BL, TAC1272_BL, VAC2047_BL, TAC1201_BL, TAC1078_BL, TAC1147_BL, VAC2028_BL, TAC1073_BL, VAC2034_BL, VAC2039_BL, TAC1167_BL, TAC1075_BL, TAC1017_BL, TAC1225_BL, TAC1122_BL, TAC1089_BL, TAC1020_BL, TAC1110_BL, TAC1055_BL, TAC1218_BL, TAC1050_BL, TAC1269_BL, TAC1038_BL, TAC1148_BL, TAC1239_BL, TAC1212_BL, VAC2048_BL, TAC1140_BL, VAC2017_BL, VAC2011_BL, VAC2010_BL, TAC1227_BL, TAC1044_BL, VAC2046_BL, VAC2026_BL, VAC2024_BL, VAC2002_BL, TAC1247_BL, VAC2021_BL, TAC1205_BL, TAC1273_BL, TAC1012_BL, TAC1202_BL, TAC1085_BL, VAC2003_BL, TAC1283_BL, TAC1194_BL, TAC1221_BL, VAC2025_BL, TAC1021_BL, VAC2033_BL, TAC1204_BL, VAC2029_BL, VAC2027_BL, TAC1105_BL, VAC2018_BL, TAC1098_BL, TAC1196_BL, VAC2032_BL, VAC2007_BL, VAC2023_BL, TAC1146_BL, TAC1119_BL, TAC1230_BL, TAC1004_BL, VAC2006_BL, TAC1215_BL, VAC2009_BL, VAC2008_BL, TAC1190_BL, TAC1200_BL, TAC1043_BL, TAC1106_BL, TAC1206_BL, TAC1199_BL, TAC1080_BL, ...]

 [140 rows x 0 columns])

In [21]:
#show_sheet_overview(df_exp_bl)
#show_dataset_structure(df_exp_bl)
inspect_omics_dataset(df_exp_bl)

===== OMICS DATASET =====

SAMPLE:

SeqId,Patient_ID,2597-8_3,2654-19_1,2788-55_1,2967-8_1,3046-31_1,4336-2_1,4337-49_2,4673-13_2,4867-15_2,...,9199-6_3,9201-13_3,9202-309_3,9204-33_3,9207-60_3,9211-19_3,9212-22_3,9213-24_3,9215-117_3,9216-100_3
SampleId,,,,,,,,,,,,,,,,,,,,,
TAC1251_BL,TAC1251,10883.7,1111.1,806.9,16868.5,989.0,455.8,135501.8,235.8,628.1,...,6355.1,3812.8,2714.1,556.2,3029.5,67230.2,3073.5,49499.8,1139.8,3983.0
TAC1055_BL,TAC1055,11341.1,1829.0,4069.6,15120.7,2095.8,928.3,94405.1,586.7,740.4,...,4501.6,4654.4,8973.6,1167.9,1751.1,53744.0,3349.7,7259.6,799.0,6012.9
TAC1212_BL,TAC1212,12009.3,1322.1,560.3,20374.6,2371.2,3856.2,125999.2,697.9,573.0,...,5764.7,3566.5,10733.2,530.0,1787.5,57312.8,1881.9,6559.9,1006.0,5415.8
TAC1239_BL,TAC1239,13333.0,2748.7,755.7,32853.2,2114.2,360.6,116396.6,387.3,513.0,...,4450.1,3871.3,5100.1,672.9,3175.9,48853.1,2451.6,29919.3,1381.4,8790.1
TAC1137_BL,TAC1137,9810.1,1406.8,811.4,9458.9,912.9,354.7,110819.5,252.8,415.2,...,5620.1,2276.4,21120.8,658.6,3028.2,57417.5,2433.1,65276.9,912.3,5497.7

SHAPE:
(140, 1311)

DTYPES:
SeqId
Patient_ID        str
2597-8_3      float64
2654-19_1     float64
2788-55_1     float64
2967-8_1      float64
               ...
9211-19_3     float64
9212-22_3     float64
9213-24_3     float64
9215-117_3    float64
9216-100_3    float64
Length: 1311, dtype: object

MISSING VALUES (Top 10):
SeqId
Patient_ID    0
2597-8_3      0
2654-19_1     0
2788-55_1     0
2967-8_1      0
3046-31_1     0
4336-2_1      0
4337-49_2     0
4673-13_2     0
4867-15_2     0
dtype: int64

DTYPES (10 random samples):
SeqId
2418-55_9     float64
8470-213_3    float64
10356-21_3    float64
2748-3_2      float64
2658-27_1     float64
6653-58_3     float64
2666-53_2     float64
4254-6_2      float64
4469-78_2     float64
4155-3_2      float64
dtype: object

SHORT NUMERIC SUMMARY (random 10 samples):

,count,mean,std,min,25%,50%,75%,max
SeqId,,,,,,,,
11067-13_3,140.0,2925.581429,11331.862452,760.6,1072.700,1429.45,1982.625,134001.0
4355-13_1,140.0,2153.324286,1555.867836,1177.5,1683.250,1898.25,2110.550,18576.8
9169-14_3,140.0,1975.699286,1806.938955,771.4,1269.275,1589.30,2172.575,20101.3
5201-50_4,140.0,793.474286,2128.966711,278.2,403.900,447.00,601.225,23127.4
4556-10_2,140.0,562.979286,129.221445,275.0,494.275,562.60,646.275,1051.5
2937-10_2,140.0,222364.665714,46358.271127,117471.0,187464.950,223824.05,252490.700,331874.8
5903-91_2,140.0,2022.783571,1364.958045,1267.6,1615.600,1829.05,2049.525,13796.3
5018-68_1,140.0,439.700714,207.152830,167.3,298.575,378.15,521.725,1421.8
4254-6_2,140.0,245.360000,312.891190,103.1,161.575,199.55,248.850,3476.5
3367-8_3,140.0,7848.112143,2894.342966,43.0,6478.100,7304.15,8443.625,20148.5

# Feature Removal
Pairwise high correlation removal (threshold=0.95)
For each correlated pair, the feature with lower variance is dropped
The feature with higher variance is always retained

In [22]:
df_exp_bl_clean, to_keep_bl, to_drop_bl = run_correlation_selection(df=df_exp_bl,
                        name='baseline expression proteomics',
                        threshold=0.95, output_dir='../../reports/feature_selection' )

df_exp_m6_clean, to_keep_m6, to_drop_m6 = run_correlation_selection(df=df_exp_6m,
                        name='6m expression proteomics',
                        threshold=0.95, output_dir='../../reports/feature_selection' )

======================================================================
FEATURE SELECTION: BASELINE EXPRESSION PROTEOMICS  (threshold = 0.95)
======================================================================
Computing correlation matrix for 1310 features (140 samples) …

Results:
  Total numeric features : 1310
  Kept                   : 1230 (93.9%)
  Dropped (redundant)    : 80 (6.1%)

Saving feature lists ...
  Saved: ../../reports/feature_selection\baseline expression proteomics_features_to_keep.txt  (1230 features)
  Saved: ../../reports/feature_selection\baseline expression proteomics_features_to_drop.txt  (80 features)
  Saved: ../../reports/feature_selection\baseline expression proteomics_feature_selection.json

======================================================================
FEATURE SELECTION: 6M EXPRESSION PROTEOMICS  (threshold = 0.95)
======================================================================
Computing correlation matrix for 1310 features (97 samples) …

Results:
  Total numeric features : 1310
  Kept                   : 1232 (94.0%)
  Dropped (redundant)    : 78 (6.0%)

Saving feature lists ...
  Saved: ../../reports/feature_selection\6m expression proteomics_features_to_keep.txt  (1232 features)
  Saved: ../../reports/feature_selection\6m expression proteomics_features_to_drop.txt  (78 features)
  Saved: ../../reports/feature_selection\6m expression proteomics_feature_selection.json

In [ ]:
df_exp_bl_clean.to_parquet('../../cleaned_datasets/exp_bl.parquet')

df_exp_m6_clean.to_parquet('../../cleaned_datasets/exp_m6.parquet')

df_exp_bl_clean.to_csv('../cleaned_datasets/exp_bl.csv')
df_exp_6m.to_csv('../cleaned_datasets/exp_m6.csv')

# Summary
After running this notebook the preprocessing has been done and the data is ready for merge or be analyzed further