## Common imports

In [1]:
import pandas as pd
from src.feature_selection_clinical import select_features
from src.config.data_contract_preprocessing_updated import CLINICAL_CONTRACT

## Load CLEANED_RA_MAP_Clinical_Figshare_17_5_21.csv (final merged clinical dataset) for feature selection

In [2]:
df_final_merged_all_clinical = pd.read_csv("../datasets/CLEANED_RA_MAP_Clinical_Figshare_17_5_21.csv")

df_final_merged_all_clinical.shape
df_final_merged_all_clinical.head()
df_final_merged_all_clinical.dtypes
df_final_merged_all_clinical.describe()
df_final_merged_all_clinical.sample(5)

,Patient_ID,Digest,Region,Hub,REGION_HUB,ACPA.POSITIVE,RHUEMATOID.FACTOR,DAS28.0M,DAS28.3M,DAS28.6M,...,intraarticular_count,intramuscular_count,first_injection,last_injection,med_event_count,unique_medications,med_total_dose,med_mean_dose,first_med_date,last_med_date
41,TAC1041,677AC6428DDF24479B6C215FB86BCD324EEABC71B529A6...,1.0,1.0,1.0,1.0,1.0,4.34,1.35,1.31,...,NaN,NaN,NaN,NaN,3.0,3.0,220.0,73.333333,2015-04-30,2015-08-04
179,TAC1179,D071C1B52F583FAFEDC5D28976979594CB8A7A00266B96...,7.0,6.0,11.0,1.0,1.0,2.23,2.78,2.55,...,NaN,NaN,NaN,NaN,1.0,1.0,200.0,200.000000,2014-11-13,2014-11-13
9,TAC1009,41AA64FCA0CF1997AFE1F04C097C9F7D680727BDBE464D...,1.0,1.0,1.0,1.0,1.0,6.11,4.25,3.38,...,0.0,2.0,2013-10-18 00:00:00.000000000,2014-10-01 00:00:00.000000000,5.0,3.0,257.5,51.500000,2013-02-11,2014-08-07
248,TAC1248,9BFE0604CD4F53CBF89EDF95353DD57D4EE442829DABA3...,10.0,5.0,10.0,1.0,1.0,3.78,4.12,2.08,...,NaN,NaN,NaN,NaN,3.0,2.0,55.0,18.333333,2014-02-28,2014-06-11
269,TAC1280,AA832EE0C90746B536FFCCE706FE2E27256C55844DCBB8...,9.0,4.0,7.0,1.0,1.0,6.66,6.94,5.20,...,4.0,3.0,2014-02-27 00:00:00.000000000,2015-12-02 00:00:00.000000000,5.0,3.0,270.0,54.000000,2013-11-18,2015-05-18

## Run feature selection on combined clinical dataset (patient level)

In [4]:
df_clinical_features = select_features(df_final_merged_all_clinical, CLINICAL_CONTRACT)

#df_clinical_features.shape
df_clinical_features.head()
#df_clinical_features.dtypes
#df_clinical_features.describe()
#df_clinical_features.columns

,Digest,Patient_ID,RACE,GENDER,ACPA.POSITIVE,RHUEMATOID.FACTOR,Erosive,ALCOHOL_Y_N,CURENT SMOKER,AGE,...,WBC.0M,FATIQUE.0M,PAIN.0M,TOTAL.SWOLLEN.0M,TOTAL.TENDER.0M,steroid_injection_count,intraarticular_count,intramuscular_count,med_event_count,unique_medications
0,B1895B6B8F7B325B977C180A25C74D079EFB5EB306693D...,TAC1000,Mixed - White and Black African ...,Female ...,1.0,1.0,0.0,1.0,1.0,31.0,...,5.9,14.0,21.0,14.0,23.0,NaN,NaN,NaN,3.0,3.0
1,59749E6B6785A9983100DA76AB0AE9484B52B2422AB362...,TAC1001,White British ...,Female ...,1.0,1.0,0.0,0.0,1.0,71.0,...,7.7,65.0,100.0,11.0,21.0,3.0,1.0,2.0,7.0,4.0
2,9C459B98832CB4E81C90B843BF7A7925D5E01A1A306586...,TAC1002,White British ...,Female ...,1.0,1.0,0.0,1.0,1.0,34.0,...,6.0,3.0,25.0,7.0,8.0,2.0,1.0,1.0,2.0,2.0
3,308098EB685FC45FA0CA61C88D25D810E16C9DADBBA77C...,TAC1003,Black or Black British - Caribbean ...,Female ...,1.0,1.0,0.0,0.0,0.0,52.0,...,5.2,7.0,32.0,3.0,14.0,1.0,0.0,1.0,4.0,3.0
4,3A9C04CAA9BBAAE16A20614D827FA3B55AA09C94F69284...,TAC1004,Black or Black British - Caribbean ...,Female ...,1.0,1.0,0.0,1.0,0.0,43.0,...,4.9,84.0,97.0,10.0,16.0,NaN,NaN,NaN,5.0,3.0